switch the server to using threadgroups
glowlabs-org/gca-backend pull request #20
Opened 2024-05-12 12:27 UTC by DavidVorick

The client needs to be switched over as well.

It got late so I didn't have time to go through and carefully review all the changes. There are probably other places in the server code where patters like `time.Sleep` or `time.After` are used, and there are probably places where goroutines are being created without being wrapped by `tg.Launch()`, all of which need to be fixed.

But I needed a nap and I wasn't sure how long I would be asleep, I wanted these changes pushed so they wouldn't be blocking anyone. Here's what the first draft looks like, probably more to come.

2024-05-12 17:03 UTC, mikew686 commented on server/report_listener_udp.go
>  			server.logger.Error("Failed to read from UDP socket: ", err)
Should test IsStopped() here and not log a spurious error.

2024-05-12 17:03 UTC, mikew686 commented on server/report_listener_udp.go
> +		readBytes, _, err := udpConn.ReadFromUDP(buffer)
Test for isStopped to avoid error log

2024-05-12 17:10 UTC, mikew686 commented on server/sync_listener_tcp.go
>  		}
Accept will log a spurious error on shutdown

2024-05-12 18:14 UTC, mikew686 commented
I'll work on the client part

2024-05-13 11:31 UTC, DavidVorick commented
This should be ready to go

2024-05-13 15:18 UTC, mikew686 requested changes

2024-05-13 15:35 UTC, DavidVorick commented on server/server.go
> +		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
I fixed this in a follow-up PR

2024-05-13 15:58 UTC, merged